In [1]:
import numpy as np

In [2]:
my_1d_array = np.zeros(10)
print(my_1d_array)

#1d array with 10 zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#If I want to change one of these values
my_1d_array[0] = 50
print(my_1d_array) #0 if element has been converted to 0

[50.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [4]:
#Now the first element [0] has been changed to 50

In [5]:
my_1d_array[3:6] = 50
print(my_1d_array) #Now these elements have been changed into 50

[50.  0.  0. 50. 50. 50.  0.  0.  0.  0.]


In [6]:
np.where(my_1d_array == 50) #It tells me where 50 is located here

(array([0, 3, 4, 5], dtype=int64),)

In [7]:
my_2d_array = np.array([[1,5,9],[8,5,5]])
print(my_2d_array)

[[1 5 9]
 [8 5 5]]


In [8]:
np.where(my_2d_array == 5) #equaled five
#5 located in row 0, column 1, row 1 and column 1, and row 1 and column 2

(array([0, 1, 1], dtype=int64), array([1, 1, 2], dtype=int64))

In [9]:
np.where(my_2d_array <5) #less than 5


(array([0], dtype=int64), array([0], dtype=int64))

In [10]:

np.where(my_2d_array >=5) #greater/equal to 5


(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [11]:

np.where(my_2d_array !=5)#Not equal to 5

(array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))

In [13]:
np.argwhere(my_2d_array == 5) #This is easier to read - all rows and columns are in one place

array([[0, 1],
       [1, 1],
       [1, 2]], dtype=int64)

In [15]:
index = np.where(my_2d_array > 5)
print(index)

(array([0, 1], dtype=int64), array([2, 0], dtype=int64))


In [16]:
index = np.where(my_2d_array > 5)
print(index)

(array([0, 1], dtype=int64), array([2, 0], dtype=int64))


In [17]:
my_2d_array[index] #Brought back conditions that were greater than 5 - numbers 8 and 9

array([9, 8])

In [23]:
my_2d_array[index] = 100
print(my_2d_array) #Index numbers were changed to equal to 100

[[  1   5 100]
 [100   5   5]]


In [24]:
np.all(my_1d_array)#False - As similar to the where function - it will default to 0 without a specific condition
#We've asked if all values are non-zero - no there are some zeros, so this is false

False

In [25]:
np.all(my_1d_array >= 0)
#Are all values greater than or equal to 0


True

In [26]:
np.all(my_1d_array >5)

#Are all values greater than 5

False

In [27]:
np.any(my_1d_array) #Are any elements non-zero?

True

In [28]:
#Combining arrays 

a = np.array([[1,2], [3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [35]:
#To stack on top of each other, use vstack

v = np.vstack((a,b))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
v = np.vstack((a,b,a,b))
print(v) #stacked 4 arrays on top of each other

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
#To stack side by side, use h stack

In [37]:
h = np.hstack((a,b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
np.hstack((a,b,a,b))

array([[1, 2, 5, 6, 1, 2, 5, 6],
       [3, 4, 7, 8, 3, 4, 7, 8]])

In [39]:
print(my_2d_array) #3 columns and 2 rows
my_2d_array.flatten() #Squished into 1d array

[[  1   5 100]
 [100   5   5]]


array([  1,   5, 100, 100,   5,   5])